<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-01T18:09:43 IST" name="Suite" finished-at="2025-04-01T18:09:47 IST" duration-ms="4962">
    <groups>
    </groups>
    <test started-at="2025-04-01T18:09:43 IST" name="Test" finished-at="2025-04-01T18:09:47 IST" duration-ms="4962">
      <class name="com.TestCase.LoginPage_TestCases">
        <test-method signature="TestValidCreds()[pri:0, instance:com.TestCase.LoginPage_TestCases@35047d03]" started-at="2025-04-01T18:09:43 IST" name="TestValidCreds" finished-at="2025-04-01T18:09:46 IST" duration-ms="3206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestValidCreds -->
        <test-method signature="TestinvalidCreds()[pri:0, instance:com.TestCase.LoginPage_TestCases@35047d03]" started-at="2025-04-01T18:09:46 IST" name="TestinvalidCreds" finished-at="2025-04-01T18:09:47 IST" duration-ms="1730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestinvalidCreds -->
      </class> <!-- com.TestCase.LoginPage_TestCases -->
      <class name="com.TettCase2.RegisterPage_test">
        <test-method signature="testtitle_data()[pri:0, instance:com.TettCase2.RegisterPage_test@3d680b5a]" started-at="2025-04-01T18:09:47 IST" name="testtitle_data" finished-at="2025-04-01T18:09:47 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<2> but was:<4>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<2> but was:<4>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:467)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
at com.TettCase2.RegisterPage_test.testtitle_data(RegisterPage_test.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtitle_data -->
        <test-method signature="testurl_data()[pri:0, instance:com.TettCase2.RegisterPage_test@3d680b5a]" started-at="2025-04-01T18:09:47 IST" name="testurl_data" finished-at="2025-04-01T18:09:47 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testurl_data -->
        <test-method signature="testvalid_data()[pri:0, instance:com.TettCase2.RegisterPage_test@3d680b5a]" started-at="2025-04-01T18:09:47 IST" name="testvalid_data" finished-at="2025-04-01T18:09:47 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testvalid_data -->
      </class> <!-- com.TettCase2.RegisterPage_test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
